# Generated by Django 5.2 on 2025-04-10 00:10

import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Naziv brenda")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Opis brenda"),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="brands/logos/"),
                ),
                ("website", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Brend",
                "verbose_name_plural": "Brendovi",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Naziv taga")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Opis taga"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tagovi",
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Ime")),
                ("phone", models.CharField(max_length=15, verbose_name="Telefon")),
                (
                    "age",
                    models.IntegerField(blank=True, null=True, verbose_name="Godine"),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "Muški"), ("female", "Ženski")],
                        max_length=10,
                        null=True,
                        verbose_name="Pol",
                    ),
                ),
                ("address", models.CharField(max_length=255, verbose_name="Adresa")),
                ("country", models.CharField(max_length=255, verbose_name="Drzava")),
                ("city", models.CharField(max_length=255, verbose_name="Grad")),
                (
                    "zip_code",
                    models.CharField(max_length=255, verbose_name="Poštanski broj"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Korisnik",
                "verbose_name_plural": "Korisnici",
            },
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(blank=True, max_length=40, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Korpa",
                "verbose_name_plural": "Korpe",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Naziv kategorije"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Opis kategorije"
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="categories/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="store.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kategorija",
                "verbose_name_plural": "Kategorije",
            },
        ),
        migrations.CreateModel(
            name="ChangeHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=100, verbose_name="Model")),
                ("object_id", models.PositiveIntegerField(verbose_name="ID objekta")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Kreiranje"),
                            ("update", "Ažuriranje"),
                            ("delete", "Brisanje"),
                        ],
                        max_length=10,
                        verbose_name="Akcija",
                    ),
                ),
                ("changes", models.JSONField(verbose_name="Promene")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Datum promene"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Korisnik",
                    ),
                ),
            ],
            options={
                "verbose_name": "Istorija promena",
                "verbose_name_plural": "Istorija promena",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_ordered", models.DateTimeField(auto_now_add=True)),
                ("complete", models.BooleanField(default=False)),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("status", models.CharField(blank=True, max_length=255, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Naziv proizvoda"),
                ),
                (
                    "short_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Kratki opis proizvoda"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Opis proizvoda"
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Šifra proizvoda"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Cena",
                    ),
                ),
                (
                    "discount",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Popust (%)",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="RSD", max_length=3, verbose_name="Valuta"
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Stopa poreza",
                    ),
                ),
                (
                    "is_taxable",
                    models.BooleanField(default=True, verbose_name="Obračunati porez"),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Cena dostave",
                    ),
                ),
                (
                    "is_shipping_free",
                    models.BooleanField(
                        default=False, verbose_name="Dostava je besplatna"
                    ),
                ),
                (
                    "is_shipping_required",
                    models.BooleanField(
                        default=True, verbose_name="Dostava je obavezna"
                    ),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Količina na stanju"
                    ),
                ),
                (
                    "min_amount",
                    models.IntegerField(default=1, verbose_name="Minimalna količina"),
                ),
                (
                    "max_amount",
                    models.IntegerField(default=0, verbose_name="Maksimalna količina"),
                ),
                (
                    "is_digital",
                    models.BooleanField(
                        default=False, verbose_name="Digitalni proizvod"
                    ),
                ),
                (
                    "digital_file",
                    models.FileField(
                        blank=True, null=True, upload_to="products/digital/"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, verbose_name="Featured proizvod"
                    ),
                ),
                (
                    "is_new",
                    models.BooleanField(default=False, verbose_name="Novi proizvod"),
                ),
                (
                    "is_best_seller",
                    models.BooleanField(
                        default=False, verbose_name="Best seller proizvod"
                    ),
                ),
                (
                    "is_top_rated",
                    models.BooleanField(
                        default=False, verbose_name="Top rated proizvod"
                    ),
                ),
                (
                    "is_on_sale",
                    models.BooleanField(default=False, verbose_name="Na popustu"),
                ),
                (
                    "is_male",
                    models.BooleanField(default=False, verbose_name="Muški proizvod"),
                ),
                (
                    "is_female",
                    models.BooleanField(default=False, verbose_name="Ženski proizvod"),
                ),
                (
                    "is_children",
                    models.BooleanField(default=False, verbose_name="Dječji proizvod"),
                ),
                (
                    "min_age",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Minimalna dob"
                    ),
                ),
                (
                    "max_age",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Maksimalna dob"
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Težina",
                    ),
                ),
                (
                    "dimensions",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Dimenzije"
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Materijal"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Boja"
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Veličina"
                    ),
                ),
                (
                    "made_in",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Proizvedeno u",
                    ),
                ),
                (
                    "made_in_country",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Država proizvodnje",
                    ),
                ),
                (
                    "made_in_city",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Grad proizvodnje",
                    ),
                ),
                (
                    "ean",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="EAN"
                    ),
                ),
                (
                    "isbn",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="ISBN"
                    ),
                ),
                (
                    "upc",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="UPC"
                    ),
                ),
                (
                    "gtin",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="GTIN"
                    ),
                ),
                (
                    "mpn",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="MPN"
                    ),
                ),
                (
                    "is_eco",
                    models.BooleanField(
                        default=False, verbose_name="Ekološki proizvod"
                    ),
                ),
                (
                    "is_organic",
                    models.BooleanField(
                        default=False, verbose_name="Organski proizvod"
                    ),
                ),
                (
                    "is_vegan",
                    models.BooleanField(default=False, verbose_name="Vegan proizvod"),
                ),
                (
                    "is_gluten_free",
                    models.BooleanField(default=False, verbose_name="Bez glutena"),
                ),
                (
                    "is_dairy_free",
                    models.BooleanField(default=False, verbose_name="Bez mleka"),
                ),
                (
                    "is_sugar_free",
                    models.BooleanField(default=False, verbose_name="Bez šećera"),
                ),
                (
                    "seo_title",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="SEO naslov"
                    ),
                ),
                (
                    "seo_description",
                    models.TextField(blank=True, null=True, verbose_name="SEO opis"),
                ),
                (
                    "seo_keywords",
                    models.TextField(
                        blank=True, null=True, verbose_name="SEO ključne reči"
                    ),
                ),
                (
                    "seo_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products/seo/",
                        verbose_name="SEO slika",
                    ),
                ),
                (
                    "num_views",
                    models.IntegerField(default=0, verbose_name="Broj pregleda"),
                ),
                (
                    "num_purchases",
                    models.IntegerField(default=0, verbose_name="Broj kupnji"),
                ),
                (
                    "num_wishlist",
                    models.IntegerField(default=0, verbose_name="Broj želja"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="store.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="store.category",
                    ),
                ),
                (
                    "sub_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sub_category",
                        to="store.category",
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, to="store.tag")),
            ],
            options={
                "verbose_name": "Proizvod",
                "verbose_name_plural": "Proizvodi",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(blank=True, default=0, null=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="store.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="store.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductFAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("answer", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faqs",
                        to="store.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "FAQ proizvoda",
                "verbose_name_plural": "FAQ proizvoda",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="products/gallery/")),
                ("is_main", models.BooleanField(default=False)),
                ("is_hover", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("alt_text", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="store.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Slika proizvoda",
                "verbose_name_plural": "Slike proizvoda",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "1 Zvezda"),
                            (2, "2 Zvezde"),
                            (3, "3 Zvezde"),
                            (4, "4 Zvezde"),
                            (5, "5 Zvezda"),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="store.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recenzija proizvoda",
                "verbose_name_plural": "Recenzije proizvoda",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("value", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specifications",
                        to="store.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Specifikacija proizvoda",
                "verbose_name_plural": "Specifikacije proizvoda",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ShippingAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                ("state", models.CharField(blank=True, max_length=255, null=True)),
                ("zipcode", models.CharField(blank=True, max_length=255, null=True)),
                ("country", models.CharField(blank=True, max_length=255, null=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="store.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UTMTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(blank=True, max_length=40)),
                ("utm_source", models.CharField(blank=True, max_length=100)),
                ("utm_medium", models.CharField(blank=True, max_length=100)),
                ("utm_campaign", models.CharField(blank=True, max_length=100)),
                ("utm_term", models.CharField(blank=True, max_length=100)),
                ("utm_content", models.CharField(blank=True, max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("converted", models.BooleanField(default=False)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "UTM Tracking",
                "verbose_name_plural": "UTM Trackings",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="store.cart",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.product"
                    ),
                ),
            ],
            options={
                "verbose_name": "Stavka korpe",
                "verbose_name_plural": "Stavke korpe",
                "unique_together": {("cart", "product")},
            },
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.product"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lista želja",
                "verbose_name_plural": "Liste želja",
                "unique_together": {("user", "product")},
            },
        ),
    ]
