# Generated by Django 5.2 on 2025-04-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="username",
        ),
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.CharField(blank=True, max_length=255, verbose_name="Adresa"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="city",
            field=models.CharField(blank=True, max_length=255, verbose_name="Grad"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="country",
            field=models.CharField(blank=True, max_length=255, verbose_name="Drzava"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(blank=True, max_length=255, verbose_name="Ime"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(blank=True, max_length=15, verbose_name="Telefon"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="zip_code",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Poštanski broj"
            ),
        ),
    ]
