# Generated by Django 5.2 on 2025-04-10 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_remove_customer_username_alter_customer_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="hover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/hover/",
                verbose_name="Hover slika",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="main_image",
            field=models.ImageField(
                default=1, upload_to="products/main/", verbose_name="Glavna slika"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gallery_images",
                to="store.product",
            ),
        ),
    ]
