# Generated by Django 5.2 on 2025-04-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_product_hover_image_product_main_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_children",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="category",
            name="is_female",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="category",
            name="is_male",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="category",
            name="min_age",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
