# Generated by Django 5.2 on 2025-04-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_category_is_children_category_is_female_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["order", "name"],
                "verbose_name": "Kategorija",
                "verbose_name_plural": "Kategorije",
            },
        ),
        migrations.RemoveField(
            model_name="category",
            name="min_age",
        ),
        migrations.AddField(
            model_name="category",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Redosled"),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_children",
            field=models.BooleanField(default=False, verbose_name="Deca"),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_female",
            field=models.BooleanField(default=False, verbose_name="Ženski"),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_male",
            field=models.BooleanField(default=False, verbose_name="Muški"),
        ),
    ]
