# Generated by Django 5.2 on 2025-04-10 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_orderitem_color_orderitem_discount_orderitem_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bundle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("required_quantity", models.PositiveIntegerField(default=2)),
                ("bundle_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "products",
                    models.ManyToManyField(related_name="bundles", to="store.product"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "promotion_type",
                    models.CharField(
                        choices=[
                            ("BUY_X_GET_Y_FREE", "Buy X Get Y Free"),
                            ("BUY_X_GET_Y_DISCOUNT", "Buy X Get Y Discount"),
                            ("CATEGORY_DISCOUNT", "Category Discount"),
                            ("TAG_DISCOUNT", "Tag Discount"),
                        ],
                        max_length=50,
                    ),
                ),
                ("required_quantity", models.PositiveIntegerField(default=2)),
                (
                    "discount_percentage",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("categories", models.ManyToManyField(blank=True, to="store.category")),
                ("tags", models.ManyToManyField(blank=True, to="store.tag")),
            ],
        ),
    ]
