# Generated by Django 5.2 on 2025-04-10 20:17

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_newslettersubscription_collection"),
    ]

    operations = [
        migrations.AddField(
            model_name="newslettersubscription",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="newslettersubscription",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="newslettersubscription",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="newslettersubscription",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Aktivna pretplata"),
        ),
        migrations.AlterField(
            model_name="newslettersubscription",
            name="subscribed_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Datum pretplate"
            ),
        ),
        migrations.AlterField(
            model_name="newslettersubscription",
            name="unsubscribed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Datum odjave"
            ),
        ),
    ]
